in:
  {
    "jsonrpc": "2.0",
    "method": "tools/call",
    "id": 2,
    "params":
      {
        "name": "list-k8s-resources",
        "arguments":
          {
            "context": "k3d-mcp-k8s-integration-test",
            "namespace": "test",
            "kind": "service",
          },
      },
  }
out:
  {
    "jsonrpc": "2.0",
    "id": 2,
    "result":
      {
        "content":
          [
            {
              "type": "text",
              "text": '{"name":"nginx-headless","namespace":"test","type":"ClusterIP","clusterIP":"None","externalIPs":null,"ports":["80/TCP"]}',
            },
          ],
        "isError": false,
      },
  }
