# Kustomization for base configuration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: git-memory-base

resources:
  - ../base/git-memory.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: git-memory-mcp-server
  app.kubernetes.io/version: "2.0.0"
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: git-memory

# Namespace for all resources
namespace: git-memory

# Images to override
images:
  - name: git-memory-mcp-server
    newTag: latest

# ConfigMap generator for environment-specific configs
configMapGenerator:
  - name: git-memory-config
    behavior: replace
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info

# Secret generator for sensitive data
secretGenerator:
  - name: git-memory-secrets
    behavior: replace
    literals:
      - GIT_MEMORY_API_KEY=your-api-key-here
      - GIT_WEBHOOK_SECRET=your-webhook-secret-here
