case: List k8s pods using tool
in:
  {
    "jsonrpc": "2.0",
    "method": "tools/call",
    "id": 2,
    "params":
      {
        "name": "list-k8s-resources",
        "arguments":
          { "context": "k3d-mcp-k8s-integration-test", "namespace": "test", "kind": "pod" },
      },
  }
out:
  {
    "jsonrpc": "2.0",
    "id": 2,
    "result":
      {
        "content":
          [
            { "type": "text", "text": '{"name":"busybox","namespace":"test"}' },
            { "type": "text", "text": '{"name":"nginx","namespace":"test"}' },
          ],
        "isError": false,
      },
  }

---
case: List k8s pods using prompt

in:
  {
    "jsonrpc": "2.0",
    "method": "prompts/get",
    "id": 3,
    "params":
      {
        "name": "list-k8s-pods",
        "arguments": { "namespace": "test" },
      },
  }

out:
  {
    "jsonrpc": "2.0",
    "id": 3,
    "result":
      {
        "description": "Pods in namespace 'test', context 'k3d-mcp-k8s-integration-test'",
        "messages":
          [
            {
              "content":
                {
                  "type": "text",
                  "text": "There are 2 pods in namespace 'test':",
                },
              "role": "user",
            },
            {
              "content":
                {
                  "type": "text",
                  "text": '{"name":"busybox","namespace":"test"}',
                },
              "role": "user",
            },
            {
              "content":
                {
                  "type": "text",
                  "text": '{"name":"nginx","namespace":"test"}',
                },
              "role": "user",
            },
          ],
      },
  }
